name: govulncheck

on:
  pull_request_target: {}
  push:
    branches: [master]
  schedule:
    - cron: '30 0 1,15 * *'

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@vmaster
      - name: Scan for Vulnerabilities in Code
        uses: Templum/govulncheck-action@<version>
        with:
          go-version: 1.18
          vulncheck-version: latest
          package: ./...
          fail-on-vuln: true
