name: test
on:
  push:
    branches:
      - "master"
  pull_request:
    types: [opened, synchronize]
    branches:
      - "*"
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: test
        run: make test

      - name: upload coverage to codecov
        uses: codecov/codecov-action@54bcd8715eee62d40e33596ef5e8f0f48dbbccab # pin@4.1.0
        with:
          files: coverage.out
          fail_ci_if_error: false
          verbose: true
